style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/boldint/test-repo
options:
  commits:
    # filters:
    #   Type: []
  commit_groups:
    # title_maps: []
  header:
    pattern: "^(feature|hotfix|bugfix|release)/(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
