name: After Push Workflow (gitversion, git-chglog, tag)

on: workflow_dispatch

jobs:
  after_push:
    name: After Push
    runs-on: ubuntu-latest
    steps:
      #############
      ### SETUP ###
      #############
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.5'

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v0.9.10
        with:
          versionSpec: '0.10.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - uses: gittools/actions/gitreleasemanager/publish@v0.9.2
        name: Publish release with GitReleaseManager
        with:
          tagName: ${{ steps.gitversion.outputs.SemVer }}
