name: After Push Workflow (gitversion, git-chglog, tag)

on: workflow_dispatch

jobs:
  after_push:
    name: After Push
    runs-on: ubuntu-latest
    steps:
      #############
      ### SETUP ###
      #############
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Bump version and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v5.6
#        with:
#          create_annotated_tag: true
#          release_branches: master, develop, qa
#          dry-run: true

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.5'

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v0.9.10
        with:
          versionSpec: '0.10.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Create tag
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.gitversion.outputs.SemVer }}",
              sha: context.sha
            })