name: After Push Workflow (gitversion, git-chglog, tag)

on:
  workflow_run:
    workflows: ["Push1 Workflow", "Push2 Workflow"]
    branches: [master, develop]
    types:
      - completed

jobs:
  after_push:
    name: After Push
    runs-on: ubuntu-latest
    steps:
      #############
      ### SETUP ###
      #############
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.5'

      ###########
      ### TAG ###
      ###########
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Create tag
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.gitversion.outputs.SemVer }}",
              sha: context.sha
            })

      #################
      ### CHANGELOG ###
      #################
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        id: github_release

      - name: Create Release
        uses: actions/create-release@v1
        #if: ${{ steps.github_release}}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ needs.github_release.outputs.changelog }}
