name: After Push Workflow (gitversion, git-chglog, tag)

on:
  workflow_run:
    workflows: ["Push1 Workflow", "Push2 Workflow"]
    branches: [master, develop]
    types:
      - completed

jobs:
  after_push:
    name: After Push
    runs-on: ubuntu-latest
    steps:
      #############
      ### SETUP ###
      #############
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.5'

      - name: Install git-chglog
        uses: craicoverflow/install-git-chglog@v1

      #################
      ### CHANGELOG ###
      #################
      - name: Create changelog
        run: |
          git-chglog -o CHANGELOG.md

      ###########
      ### TAG ###
      ###########
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Create tag
        id: create_tag
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.gitversion.outputs.SemVer }}",
              sha: context.sha
            })

      ###########################
      ### PUSH BACK TO BRANCH ###
      ###########################
      - name: Push changed files to branch
        uses: mikeal/publish-to-github-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH_NAME: ${{ github.ref }}
