name: After Push Workflow (gitversion, git-chglog, tag)

on:
  workflow_run:
    workflows: ["Push Workflow"]
    branches: [master, develop]
    types:
      - completed

jobs:
  after_push:
    name: After Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.5'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Create tag
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.gitversion.outputs.SemVer }}",
              sha: context.sha
            })
