name: Push1 Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'ignore_for_push/**'

jobs:
  push1:
    name: Push1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NoOP step
        run: echo "NoOP!"
